### ISSUE TITLE
build failed on Mac OS X 10.6.4

### ISSUE THREAD

**Issue by attilacsordas** [anthonyu/Sizzle#1]
This is what I get when I try to compile with ant on the top dir:

README      conf        lib     test
build.xml   docs        src
unknown-00-26-bb-00-4b-f5:anthonyu-Sizzle-17d856b miklo$ ant
Buildfile: build.xml

init:
    [mkdir] Created dir: /Users/miklo/anthonyu-Sizzle-17d856b/build/java/sizzle/parser
    [mkdir] Created dir: /Users/miklo/anthonyu-Sizzle-17d856b/build/javacc
    [mkdir] Created dir: /Users/miklo/anthonyu-Sizzle-17d856b/build/classes
    [mkdir] Created dir: /Users/miklo/anthonyu-Sizzle-17d856b/build/testclasses
    [mkdir] Created dir: /Users/miklo/anthonyu-Sizzle-17d856b/dist

translate-proto:

BUILD FAILED
/Users/miklo/anthonyu-Sizzle-17d856b/build.xml:20: Execute failed: java.io.IOException: Cannot run program "protoc": error=2, No such file or directory

Total time: 0 seconds

**Comment by anthonyu** [comment]
OK, this should be fixed now.  I precompiled the protocol buffers code, so you no longer need to have protoc installed.

Thanks for the report!

**Comment by attilacsordas** [comment]
this is what I get now what ant, still failed:

Buildfile: build.xml

init:
    [mkdir] Created dir: /Users/miklo/anthonyu-Sizzle-8d9d8d7/build/java/sizzle/parser
    [mkdir] Created dir: /Users/miklo/anthonyu-Sizzle-8d9d8d7/build/javacc
    [mkdir] Created dir: /Users/miklo/anthonyu-Sizzle-8d9d8d7/build/classes
    [mkdir] Created dir: /Users/miklo/anthonyu-Sizzle-8d9d8d7/build/testclasses
    [mkdir] Created dir: /Users/miklo/anthonyu-Sizzle-8d9d8d7/dist

tree:
     [java] JTB version 1.3.2
     [java] JTB:  Reading from ../../../../src/jtb/sizzle.jtb...
     [java] JTB:  Input file parsed successfully.
     [java] JTB:  "../../../javacc/sizzle.jj" generated to current directory.
     [java] JTB:  Syntax tree Java source files generated to directory "syntaxtree".
     [java] 
     [java] JTB:  "GJVisitor.java" generated to directory "visitor".
     [java] JTB:  "Visitor.java" generated to directory "visitor".
     [java] JTB:  "GJNoArguVisitor.java" generated to directory "visitor".
     [java] JTB:  "GJVoidVisitor.java" generated to directory "visitor".
     [java] JTB:  "GJDepthFirst.java" generated to directory "visitor".
     [java] JTB:  "DepthFirstVisitor.java" generated to directory "visitor".
     [java] JTB:  "GJNoArguDepthFirst.java" generated to directory "visitor".
     [java] JTB:  "GJVoidDepthFirst.java" generated to directory "visitor".
     [java] 

parser:
   [javacc] Java Compiler Compiler Version 5.0 (Parser Generator)
   [javacc](type "javacc" with no arguments for help)
   [javacc] Reading from file /Users/miklo/anthonyu-Sizzle-8d9d8d7/build/javacc/sizzle.jj . . .
   [javacc] File "TokenMgrError.java" does not exist.  Will create one.
   [javacc] File "ParseException.java" does not exist.  Will create one.
   [javacc] File "Token.java" does not exist.  Will create one.
   [javacc] File "JavaCharStream.java" does not exist.  Will create one.
   [javacc] Parser generated successfully.

compile-generated:
    [javac] Compiling 67 source files to /Users/miklo/anthonyu-Sizzle-8d9d8d7/build/classes

BUILD FAILED
/Users/miklo/anthonyu-Sizzle-8d9d8d7/build.xml:46: srcdir "/Users/miklo/anthonyu-Sizzle-8d9d8d7/src/protobufs" does not exist!

Total time: 5 seconds

**Comment by anthonyu** [comment]
I think that was fixed in 

https://github.com/anthonyu/Sizzle/commit/aa34d107044eb772fcebc37d3605a43f61e748b4

Can you pull the latest and let me know if you still see this problem?

Thanks!
Anthony

**Comment by attilacsordas** [comment]
Hey, Anthony: finally it worked:
BUILD SUCCESSFUL
Total time: 1 minute 14 seconds

looking forward to my first executed helloworld finally!

**Comment by anthonyu** [comment]
Awesome! Thanks for all your help.
